//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerShell.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PowerShellResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PowerShellResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerShell.Infrastructure.PowerShellResources", typeof(PowerShellResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon.
        /// </summary>
        internal static string AutoLogonSettinigsRootKey {
            get {
                return ResourceManager.GetString("AutoLogonSettinigsRootKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer &apos;{0}&apos; has a restart pending!.
        /// </summary>
        internal static string Computer0HasARestartPending {
            get {
                return ResourceManager.GetString("Computer0HasARestartPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PendingFileRenameOperations.
        /// </summary>
        internal static string PendingFileRenameOperations {
            get {
                return ResourceManager.GetString("PendingFileRenameOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot Machine Immediately.
        /// </summary>
        internal static string RebootMachineImmediately {
            get {
                return ResourceManager.GetString("RebootMachineImmediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot Not Required.
        /// </summary>
        internal static string RebootNotRequired {
            get {
                return ResourceManager.GetString("RebootNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RebootPending.
        /// </summary>
        internal static string RebootPending {
            get {
                return ResourceManager.GetString("RebootPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM\ControlSet001\Control\ComputerName\ActiveComputerName.
        /// </summary>
        internal static string RegistryKeyActiveComputerName {
            get {
                return ResourceManager.GetString("RegistryKeyActiveComputerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing.
        /// </summary>
        internal static string RegistryKeyComponentBasedServicing {
            get {
                return ResourceManager.GetString("RegistryKeyComponentBasedServicing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM\ControlSet001\Control\ComputerName\ComputerName.
        /// </summary>
        internal static string RegistryKeyComputerName {
            get {
                return ResourceManager.GetString("RegistryKeyComputerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM\CurrentControlSet\Control\Session Manager.
        /// </summary>
        internal static string RegistryKeySessionManager {
            get {
                return ResourceManager.GetString("RegistryKeySessionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update.
        /// </summary>
        internal static string RegistryKeyWindowsUpdateAutoUpdate {
            get {
                return ResourceManager.GetString("RegistryKeyWindowsUpdateAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiresReboot.
        /// </summary>
        internal static string RequiresReboot {
            get {
                return ResourceManager.GetString("RequiresReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart computer {0}.
        /// </summary>
        internal static string RestartComputer0 {
            get {
                return ResourceManager.GetString("RestartComputer0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce.
        /// </summary>
        internal static string RunOnceRootKey {
            get {
                return ResourceManager.GetString("RunOnceRootKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Pending Restart.
        /// </summary>
        internal static string TestPendingRestart {
            get {
                return ResourceManager.GetString("TestPendingRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no pending restart for Computer &apos;{0}&apos;.
        /// </summary>
        internal static string ThereIsNoPendingRestartForComputer0 {
            get {
                return ResourceManager.GetString("ThereIsNoPendingRestartForComputer0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}{2}.
        /// </summary>
        internal static string WriteLineString {
            get {
                return ResourceManager.GetString("WriteLineString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x.txt.
        /// </summary>
        internal static string XTxtFile {
            get {
                return ResourceManager.GetString("XTxtFile", resourceCulture);
            }
        }
    }
}
