// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.



//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Xml.Serialization;


namespace Microsoft.PowerShell.Cmdletization.Xml
{
    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public enum ConfirmImpact
    {
        /// <remarks />
        None,
        /// <remarks />
        Low,
        /// <remarks />
        Medium,
        /// <remarks />
        High
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11", IncludeInSchema = false)]
    public enum ItemsChoiceType
    {
        /// <remarks />
        ExcludeQuery,
        /// <remarks />
        MaxValueQuery,
        /// <remarks />
        MinValueQuery,
        /// <remarks />
        RegularQuery
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    [XmlRoot(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11", IsNullable = false)]
    public partial class PowerShellMetadata
    {
	private ClassMetadata _class;
	private EnumMetadataEnum[] _enums;

        /// <remarks />
        public ClassMetadata Class
        {
            get
            {
                return _class;
            }
            set
            {
                _class = value;
            }
        }

        /// <remarks />
        [XmlArrayItem("Enum", IsNullable = false)]
        public EnumMetadataEnum[] Enums
        {
            get
            {
                return _enums;
            }
            set
            {
                _enums = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class ClassMetadata
    {
        private string _version;
        private string _defaultNoun;
        private ClassMetadataInstanceCmdlets _instanceCmdlets;
        private StaticCmdletMetadata[] _staticCmdlets;
        private ClassMetadataData[] _cmdletAdapterPrivateData;
        private string _cmdletAdapter;
        private string _className;
        private string _classVersion;

        /// <remarks />
        public string Version
        {
            get
            {
                return _version;
            }
            set
            {
                _version = value;
            }
        }

        /// <remarks />
        public string DefaultNoun
        {
            get
            {
                return _defaultNoun;
            }
            set
            {
                _defaultNoun = value;
            }
        }

        /// <remarks />
        public ClassMetadataInstanceCmdlets InstanceCmdlets
        {
            get
            {
                return _instanceCmdlets;
            }
            set
            {
                _instanceCmdlets = value;
            }
        }

        /// <remarks />
        [XmlArrayItem("Cmdlet", IsNullable = false)]
        public StaticCmdletMetadata[] StaticCmdlets
        {
            get
            {
                return _staticCmdlets;
            }
            set
            {
                _staticCmdlets = value;
            }
        }

        /// <remarks />
        [XmlArrayItem("Data", IsNullable = false)]
        public ClassMetadataData[] CmdletAdapterPrivateData
        {
            get
            {
                return _cmdletAdapterPrivateData;
            }
            set
            {
                _cmdletAdapterPrivateData = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public string CmdletAdapter
        {
            get
            {
                return _cmdletAdapter;
            }
            set
            {
                _cmdletAdapter = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public string ClassName
        {
            get
            {
                return _className;
            }
            set
            {
                _className = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public string ClassVersion
        {
            get
            {
                return _classVersion;
            }
            set
            {
                _classVersion = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class ClassMetadataInstanceCmdlets
    {
        private GetCmdletParameters _getCmdletParameters;
        private GetCmdletMetadata _getCmdlet;
        private InstanceCmdletMetadata[] _cmdlet;

        /// <remarks />
        public GetCmdletParameters GetCmdletParameters
        {
            get
            {
                return _getCmdletParameters;
            }
            set
            {
                _getCmdletParameters = value;
            }
        }

        /// <remarks />
        public GetCmdletMetadata GetCmdlet
        {
            get
            {
                return _getCmdlet;
            }
            set
            {
                _getCmdlet = value;
            }
        }

        /// <remarks />
        [XmlElement("Cmdlet")]
        public InstanceCmdletMetadata[] Cmdlet
        {
            get
            {
                return _cmdlet;
            }
            set
            {
                _cmdlet = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class GetCmdletParameters
    {
        private PropertyMetadata[] _queryableProperties;
        private Association[] _queryableAssociations;
        private QueryOption[] _queryOptions;
        private string _defaultCmdletParameterSet;

        /// <remarks />
        [XmlArrayItem("Property", IsNullable = false)]
        public PropertyMetadata[] QueryableProperties
        {
            get
            {
                return _queryableProperties;
            }
            set
            {
                _queryableProperties = value;
            }
        }

        /// <remarks />
        [XmlArrayItem(IsNullable = false)]
        public Association[] QueryableAssociations
        {
            get
            {
                return _queryableAssociations;
            }
            set
            {
                _queryableAssociations = value;
            }
        }

        /// <remarks />
        [XmlArrayItem("Option", IsNullable = false)]
        public QueryOption[] QueryOptions
        {
            get
            {
                return _queryOptions;
            }
            set
            {
                _queryOptions = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public string DefaultCmdletParameterSet
        {
            get
            {
                return _defaultCmdletParameterSet;
            }
            set
            {
                _defaultCmdletParameterSet = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class PropertyMetadata
    {
        private TypeMetadata _type;
        private PropertyQuery[] _items;
        private ItemsChoiceType[] _itemsElementName;
        private string _propertyName;

        /// <remarks />
        public TypeMetadata Type
        {
            get
            {
                return _type;
            }
            set
            {
                _type = value;
            }
        }

        /// <remarks />
        [XmlElement("ExcludeQuery", typeof(WildcardablePropertyQuery))]
        [XmlElement("MaxValueQuery", typeof(PropertyQuery))]
        [XmlElement("MinValueQuery", typeof(PropertyQuery))]
        [XmlElement("RegularQuery", typeof(WildcardablePropertyQuery))]
        [XmlChoiceIdentifier("ItemsElementName")]
        public PropertyQuery[] Items
        {
            get
            {
                return _items;
            }
            set
            {
                _items = value;
            }
        }

        /// <remarks />
        [XmlElement("ItemsElementName")]
        [XmlIgnore]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return _itemsElementName;
            }
            set
            {
                _itemsElementName = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public string PropertyName
        {
            get
            {
                return _propertyName;
            }
            set
            {
                _propertyName = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class TypeMetadata
    {
        private string _pSType;
        private string _eTSType;

        /// <remarks />
        [XmlAttribute]
        public string PSType
        {
            get
            {
                return _pSType;
            }
            set
            {
                _pSType = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public string ETSType
        {
            get
            {
                return _eTSType;
            }
            set
            {
                _eTSType = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class Association
    {
        private AssociationAssociatedInstance _associatedInstance;
        private string _association1;
        private string _sourceRole;
        private string _resultRole;

        /// <remarks />
        public AssociationAssociatedInstance AssociatedInstance
        {
            get
            {
                return _associatedInstance;
            }
            set
            {
                _associatedInstance = value;
            }
        }

        /// <remarks />
        [XmlAttribute("Association")]
        public string Association1
        {
            get
            {
                return _association1;
            }
            set
            {
                _association1 = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public string SourceRole
        {
            get
            {
                return _sourceRole;
            }
            set
            {
                _sourceRole = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public string ResultRole
        {
            get
            {
                return _resultRole;
            }
            set
            {
                _resultRole = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class AssociationAssociatedInstance
    {
        private TypeMetadata _type;
        private CmdletParameterMetadataForGetCmdletFilteringParameter _cmdletParameterMetadata;

        /// <remarks />
        public TypeMetadata Type
        {
            get
            {
                return _type;
            }
            set
            {
                _type = value;
            }
        }

        /// <remarks />
        public CmdletParameterMetadataForGetCmdletFilteringParameter CmdletParameterMetadata
        {
            get
            {
                return _cmdletParameterMetadata;
            }
            set
            {
                _cmdletParameterMetadata = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class CmdletParameterMetadataForGetCmdletFilteringParameter : CmdletParameterMetadataForGetCmdletParameter
    {
        private bool _errorOnNoMatch;
        private bool _errorOnNoMatchSpecified;

        /// <remarks />
        [XmlAttribute]
        public bool ErrorOnNoMatch
        {
            get
            {
                return _errorOnNoMatch;
            }
            set
            {
                _errorOnNoMatch = value;
            }
        }

        /// <remarks />
        [XmlIgnore]
        public bool ErrorOnNoMatchSpecified
        {
            get
            {
                return _errorOnNoMatchSpecified;
            }
            set
            {
                _errorOnNoMatchSpecified = value;
            }
        }
    }

    /// <remarks />
    [XmlInclude(typeof(CmdletParameterMetadataForGetCmdletFilteringParameter))]
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class CmdletParameterMetadataForGetCmdletParameter : CmdletParameterMetadata
    {
        private bool _valueFromPipeline;
        private bool _valueFromPipelineSpecified;
        private bool _valueFromPipelineByPropertyName;
        private bool _valueFromPipelineByPropertyNameSpecified;
        private string[] _cmdletParameterSets;

        /// <remarks />
        [XmlAttribute]
        public bool ValueFromPipeline
        {
            get
            {
                return _valueFromPipeline;
            }
            set
            {
                _valueFromPipeline = value;
            }
        }

        /// <remarks />
        [XmlIgnore]
        public bool ValueFromPipelineSpecified
        {
            get
            {
                return _valueFromPipelineSpecified;
            }
            set
            {
                _valueFromPipelineSpecified = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public bool ValueFromPipelineByPropertyName
        {
            get
            {
                return _valueFromPipelineByPropertyName;
            }
            set
            {
                _valueFromPipelineByPropertyName = value;
            }
        }

        /// <remarks />
        [XmlIgnore]
        public bool ValueFromPipelineByPropertyNameSpecified
        {
            get
            {
                return _valueFromPipelineByPropertyNameSpecified;
            }
            set
            {
                _valueFromPipelineByPropertyNameSpecified = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public string[] CmdletParameterSets
        {
            get
            {
                return _cmdletParameterSets;
            }
            set
            {
                _cmdletParameterSets = value;
            }
        }
    }

    /// <remarks />
    [XmlInclude(typeof(CmdletParameterMetadataForGetCmdletParameter))]
    [XmlInclude(typeof(CmdletParameterMetadataForGetCmdletFilteringParameter))]
    [XmlInclude(typeof(CmdletParameterMetadataForInstanceMethodParameter))]
    [XmlInclude(typeof(CmdletParameterMetadataForStaticMethodParameter))]
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class CmdletParameterMetadata
    {
        private object _allowEmptyCollection;
        private object _allowEmptyString;
        private object _allowNull;
        private object _validateNotNull;
        private object _validateNotNullOrEmpty;
        private CmdletParameterMetadataValidateCount _validateCount;
        private CmdletParameterMetadataValidateLength _validateLength;
        private CmdletParameterMetadataValidateRange _validateRange;
        private string[] _validateSet;
        private ObsoleteAttributeMetadata _obsolete;
        private bool _isMandatory;
        private bool _isMandatorySpecified;
        private string[] _aliases;
        private string _pSName;
        private string _position;

        /// <remarks />
        public object AllowEmptyCollection
        {
            get
            {
                return _allowEmptyCollection;
            }
            set
            {
                _allowEmptyCollection = value;
            }
        }

        /// <remarks />
        public object AllowEmptyString
        {
            get
            {
                return _allowEmptyString;
            }
            set
            {
                _allowEmptyString = value;
            }
        }

        /// <remarks />
        public object AllowNull
        {
            get
            {
                return _allowNull;
            }
            set
            {
                _allowNull = value;
            }
        }

        /// <remarks />
        public object ValidateNotNull
        {
            get
            {
                return _validateNotNull;
            }
            set
            {
                _validateNotNull = value;
            }
        }

        /// <remarks />
        public object ValidateNotNullOrEmpty
        {
            get
            {
                return _validateNotNullOrEmpty;
            }
            set
            {
                _validateNotNullOrEmpty = value;
            }
        }

        /// <remarks />
        public CmdletParameterMetadataValidateCount ValidateCount
        {
            get
            {
                return _validateCount;
            }
            set
            {
                _validateCount = value;
            }
        }

        /// <remarks />
        public CmdletParameterMetadataValidateLength ValidateLength
        {
            get
            {
                return _validateLength;
            }
            set
            {
                _validateLength = value;
            }
        }

        /// <remarks />
        public CmdletParameterMetadataValidateRange ValidateRange
        {
            get
            {
                return _validateRange;
            }
            set
            {
                _validateRange = value;
            }
        }

        /// <remarks />
        [XmlArrayItem("AllowedValue", IsNullable = false)]
        public string[] ValidateSet
        {
            get
            {
                return _validateSet;
            }
            set
            {
                _validateSet = value;
            }
        }

        /// <remarks />
        public ObsoleteAttributeMetadata Obsolete
        {
            get
            {
                return _obsolete;
            }
            set
            {
                _obsolete = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public bool IsMandatory
        {
            get
            {
                return _isMandatory;
            }
            set
            {
                _isMandatory = value;
            }
        }

        /// <remarks />
        [XmlIgnore]
        public bool IsMandatorySpecified
        {
            get
            {
                return _isMandatorySpecified;
            }
            set
            {
                _isMandatorySpecified = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public string[] Aliases
        {
            get
            {
                return _aliases;
            }
            set
            {
                _aliases = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public string PSName
        {
            get
            {
                return _pSName;
            }
            set
            {
                _pSName = value;
            }
        }

        /// <remarks />
        [XmlAttribute(DataType = "nonNegativeInteger")]
        public string Position
        {
            get
            {
                return _position;
            }
            set
            {
                _position = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class CmdletParameterMetadataValidateCount
    {
        private string _min;
        private string _max;

        /// <remarks />
        [XmlAttribute(DataType = "nonNegativeInteger")]
        public string Min
        {
            get
            {
                return _min;
            }
            set
            {
                _min = value;
            }
        }

        /// <remarks />
        [XmlAttribute(DataType = "nonNegativeInteger")]
        public string Max
        {
            get
            {
                return _max;
            }
            set
            {
                _max = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class CmdletParameterMetadataValidateLength
    {
        private string _min;
        private string _max;

        /// <remarks />
        [XmlAttribute(DataType = "nonNegativeInteger")]
        public string Min
        {
            get
            {
                return _min;
            }
            set
            {
                _min = value;
            }
        }

        /// <remarks />
        [XmlAttribute(DataType = "nonNegativeInteger")]
        public string Max
        {
            get
            {
                return _max;
            }
            set
            {
                _max = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class CmdletParameterMetadataValidateRange
    {
        private string _min;
        private string _max;

        /// <remarks />
        [XmlAttribute(DataType = "integer")]
        public string Min
        {
            get
            {
                return _min;
            }
            set
            {
                _min = value;
            }
        }

        /// <remarks />
        [XmlAttribute(DataType = "integer")]
        public string Max
        {
            get
            {
                return _max;
            }
            set
            {
                _max = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class ObsoleteAttributeMetadata
    {
        private string _message;

        /// <remarks />
        [XmlAttribute]
        public string Message
        {
            get
            {
                return _message;
            }
            set
            {
                _message = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class CmdletParameterMetadataForInstanceMethodParameter : CmdletParameterMetadata
    {
        private bool _valueFromPipelineByPropertyName;
        private bool _valueFromPipelineByPropertyNameSpecified;

        /// <remarks />
        [XmlAttribute]
        public bool ValueFromPipelineByPropertyName
        {
            get
            {
                return _valueFromPipelineByPropertyName;
            }
            set
            {
                _valueFromPipelineByPropertyName = value;
            }
        }

        /// <remarks />
        [XmlIgnore]
        public bool ValueFromPipelineByPropertyNameSpecified
        {
            get
            {
                return _valueFromPipelineByPropertyNameSpecified;
            }
            set
            {
                _valueFromPipelineByPropertyNameSpecified = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class CmdletParameterMetadataForStaticMethodParameter : CmdletParameterMetadata
    {
        private bool _valueFromPipeline;
        private bool _valueFromPipelineSpecified;
        private bool _valueFromPipelineByPropertyName;
        private bool _valueFromPipelineByPropertyNameSpecified;

        /// <remarks />
        [XmlAttribute]
        public bool ValueFromPipeline
        {
            get
            {
                return _valueFromPipeline;
            }
            set
            {
                _valueFromPipeline = value;
            }
        }

        /// <remarks />
        [XmlIgnore]
        public bool ValueFromPipelineSpecified
        {
            get
            {
                return _valueFromPipelineSpecified;
            }
            set
            {
                _valueFromPipelineSpecified = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public bool ValueFromPipelineByPropertyName
        {
            get
            {
                return _valueFromPipelineByPropertyName;
            }
            set
            {
                _valueFromPipelineByPropertyName = value;
            }
        }

        /// <remarks />
        [XmlIgnore]
        public bool ValueFromPipelineByPropertyNameSpecified
        {
            get
            {
                return _valueFromPipelineByPropertyNameSpecified;
            }
            set
            {
                _valueFromPipelineByPropertyNameSpecified = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class QueryOption
    {
        private TypeMetadata _type;
        private CmdletParameterMetadataForGetCmdletParameter _cmdletParameterMetadata;
        private string _optionName;

        /// <remarks />
        public TypeMetadata Type
        {
            get
            {
                return _type;
            }
            set
            {
                _type = value;
            }
        }

        /// <remarks />
        public CmdletParameterMetadataForGetCmdletParameter CmdletParameterMetadata
        {
            get
            {
                return _cmdletParameterMetadata;
            }
            set
            {
                _cmdletParameterMetadata = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public string OptionName
        {
            get
            {
                return _optionName;
            }
            set
            {
                _optionName = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class GetCmdletMetadata
    {
        private CommonCmdletMetadata _cmdletMetadata;
        private GetCmdletParameters _getCmdletParameters;

        /// <remarks />
        public CommonCmdletMetadata CmdletMetadata
        {
            get
            {
                return _cmdletMetadata;
            }
            set
            {
                _cmdletMetadata = value;
            }
        }

        /// <remarks />
        public GetCmdletParameters GetCmdletParameters
        {
            get
            {
                return _getCmdletParameters;
            }
            set
            {
                _getCmdletParameters = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class CommonCmdletMetadata
    {
        private ObsoleteAttributeMetadata _obsolete;
        private string _verb;
        private string _noun;
        private string[] _aliases;
        private ConfirmImpact _confirmImpact;
        private bool _confirmImpactSpecified;
        private string _helpUri;

        /// <remarks />
        public ObsoleteAttributeMetadata Obsolete
        {
            get
            {
                return _obsolete;
            }
            set
            {
                _obsolete = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public string Verb
        {
            get
            {
                return _verb;
            }
            set
            {
                _verb = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public string Noun
        {
            get
            {
                return _noun;
            }
            set
            {
                _noun = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public string[] Aliases
        {
            get
            {
                return _aliases;
            }
            set
            {
                _aliases = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public ConfirmImpact ConfirmImpact
        {
            get
            {
                return _confirmImpact;
            }
            set
            {
                _confirmImpact = value;
            }
        }

        /// <remarks />
        [XmlIgnore]
        public bool ConfirmImpactSpecified
        {
            get
            {
                return _confirmImpactSpecified;
            }
            set
            {
                _confirmImpactSpecified = value;
            }
        }

        /// <remarks />
        [XmlAttribute(DataType = "anyURI")]
        public string HelpUri
        {
            get
            {
                return _helpUri;
            }
            set
            {
                _helpUri = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class StaticCmdletMetadata
    {
        private StaticCmdletMetadataCmdletMetadata _cmdletMetadata;
        private StaticMethodMetadata[] _method;

        /// <remarks />
        public StaticCmdletMetadataCmdletMetadata CmdletMetadata
        {
            get
            {
                return _cmdletMetadata;
            }
            set
            {
                _cmdletMetadata = value;
            }
        }

        /// <remarks />
        [XmlElement("Method")]
        public StaticMethodMetadata[] Method
        {
            get
            {
                return _method;
            }
            set
            {
                _method = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class StaticCmdletMetadataCmdletMetadata : CommonCmdletMetadata
    {
        private string _defaultCmdletParameterSet;

        /// <remarks />
        [XmlAttribute]
        public string DefaultCmdletParameterSet
        {
            get
            {
                return _defaultCmdletParameterSet;
            }
            set
            {
                _defaultCmdletParameterSet = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class StaticMethodMetadata : CommonMethodMetadata
    {
        private StaticMethodParameterMetadata[] _parameters;
        private string _cmdletParameterSet;

        /// <remarks />
        [XmlArrayItem("Parameter", IsNullable = false)]
        public StaticMethodParameterMetadata[] Parameters
        {
            get
            {
                return _parameters;
            }
            set
            {
                _parameters = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public string CmdletParameterSet
        {
            get
            {
                return _cmdletParameterSet;
            }
            set
            {
                _cmdletParameterSet = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class StaticMethodParameterMetadata : CommonMethodParameterMetadata
    {
        private CmdletParameterMetadataForStaticMethodParameter _cmdletParameterMetadata;
        private CmdletOutputMetadata _cmdletOutputMetadata;

        /// <remarks />
        public CmdletParameterMetadataForStaticMethodParameter CmdletParameterMetadata
        {
            get
            {
                return _cmdletParameterMetadata;
            }
            set
            {
                _cmdletParameterMetadata = value;
            }
        }

        /// <remarks />
        public CmdletOutputMetadata CmdletOutputMetadata
        {
            get
            {
                return _cmdletOutputMetadata;
            }
            set
            {
                _cmdletOutputMetadata = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class CmdletOutputMetadata
    {
        private object _errorCode;
        private string _pSName;

        /// <remarks />
        public object ErrorCode
        {
            get
            {
                return _errorCode;
            }
            set
            {
                _errorCode = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public string PSName
        {
            get
            {
                return _pSName;
            }
            set
            {
                _pSName = value;
            }
        }
    }

    /// <remarks />
    [XmlInclude(typeof(InstanceMethodParameterMetadata))]
    [XmlInclude(typeof(StaticMethodParameterMetadata))]
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class CommonMethodParameterMetadata
    {
        private TypeMetadata _type;
        private string _parameterName;
        private string _defaultValue;

        /// <remarks />
        public TypeMetadata Type
        {
            get
            {
                return _type;
            }
            set
            {
                _type = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public string ParameterName
        {
            get
            {
                return _parameterName;
            }
            set
            {
                _parameterName = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public string DefaultValue
        {
            get
            {
                return _defaultValue;
            }
            set
            {
                _defaultValue = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class InstanceMethodParameterMetadata : CommonMethodParameterMetadata
    {
        private CmdletParameterMetadataForInstanceMethodParameter _cmdletParameterMetadata;
        private CmdletOutputMetadata _cmdletOutputMetadata;

        /// <remarks />
        public CmdletParameterMetadataForInstanceMethodParameter CmdletParameterMetadata
        {
            get
            {
                return _cmdletParameterMetadata;
            }
            set
            {
                _cmdletParameterMetadata = value;
            }
        }

        /// <remarks />
        public CmdletOutputMetadata CmdletOutputMetadata
        {
            get
            {
                return _cmdletOutputMetadata;
            }
            set
            {
                _cmdletOutputMetadata = value;
            }
        }
    }

    /// <remarks />
    [XmlInclude(typeof(InstanceMethodMetadata))]
    [XmlInclude(typeof(StaticMethodMetadata))]
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class CommonMethodMetadata
    {
        private CommonMethodMetadataReturnValue _returnValue;
        private string _methodName;

        /// <remarks />
        public CommonMethodMetadataReturnValue ReturnValue
        {
            get
            {
                return _returnValue;
            }
            set
            {
                _returnValue = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public string MethodName
        {
            get
            {
                return _methodName;
            }
            set
            {
                _methodName = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class CommonMethodMetadataReturnValue
    {
        private TypeMetadata _type;
        private CmdletOutputMetadata _cmdletOutputMetadata;

        /// <remarks />
        public TypeMetadata Type
        {
            get
            {
                return _type;
            }
            set
            {
                _type = value;
            }
        }

        /// <remarks />
        public CmdletOutputMetadata CmdletOutputMetadata
        {
            get
            {
                return _cmdletOutputMetadata;
            }
            set
            {
                _cmdletOutputMetadata = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class InstanceMethodMetadata : CommonMethodMetadata
    {
        private InstanceMethodParameterMetadata[] _parameters;

        /// <remarks />
        [XmlArrayItem("Parameter", IsNullable = false)]
        public InstanceMethodParameterMetadata[] Parameters
        {
            get
            {
                return _parameters;
            }
            set
            {
                _parameters = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class InstanceCmdletMetadata
    {
        private CommonCmdletMetadata _cmdletMetadata;
        private InstanceMethodMetadata _method;
        private GetCmdletParameters _getCmdletParameters;

        /// <remarks />
        public CommonCmdletMetadata CmdletMetadata
        {
            get
            {
                return _cmdletMetadata;
            }
            set
            {
                _cmdletMetadata = value;
            }
        }

        /// <remarks />
        public InstanceMethodMetadata Method
        {
            get
            {
                return _method;
            }
            set
            {
                _method = value;
            }
        }

        /// <remarks />
        public GetCmdletParameters GetCmdletParameters
        {
            get
            {
                return _getCmdletParameters;
            }
            set
            {
                _getCmdletParameters = value;
            }
        }
    }

    /// <remarks />
    [XmlInclude(typeof(WildcardablePropertyQuery))]
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class PropertyQuery
    {
        private CmdletParameterMetadataForGetCmdletFilteringParameter _cmdletParameterMetadata;

        /// <remarks />
        public CmdletParameterMetadataForGetCmdletFilteringParameter CmdletParameterMetadata
        {
            get
            {
                return _cmdletParameterMetadata;
            }
            set
            {
                _cmdletParameterMetadata = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class WildcardablePropertyQuery : PropertyQuery
    {
        private bool _allowGlobbing;
        private bool _allowGlobbingSpecified;

        /// <remarks />
        [XmlAttribute]
        public bool AllowGlobbing
        {
            get
            {
                return _allowGlobbing;
            }
            set
            {
                _allowGlobbing = value;
            }
        }

        /// <remarks />
        [XmlIgnore]
        public bool AllowGlobbingSpecified
        {
            get
            {
                return _allowGlobbingSpecified;
            }
            set
            {
                _allowGlobbingSpecified = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class ClassMetadataData
    {
        private string _name;
        private string _value;

        /// <remarks />
        [XmlAttribute]
        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }

        /// <remarks />
        [XmlText]
        public string Value
        {
            get
            {
                return _value;
            }
            set
            {
                _value = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class EnumMetadataEnum
    {
        private EnumMetadataEnumValue[] _value;
        private string _enumName;
        private string _underlyingType;
        private bool _bitwiseFlags;
        private bool _bitwiseFlagsSpecified;

        /// <remarks />
        [XmlElement("Value")]
        public EnumMetadataEnumValue[] Value
        {
            get
            {
                return _value;
            }
            set
            {
                _value = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public string EnumName
        {
            get
            {
                return _enumName;
            }
            set
            {
                _enumName = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public string UnderlyingType
        {
            get
            {
                return _underlyingType;
            }
            set
            {
                _underlyingType = value;
            }
        }

        /// <remarks />
        [XmlAttribute]
        public bool BitwiseFlags
        {
            get
            {
                return _bitwiseFlags;
            }
            set
            {
                _bitwiseFlags = value;
            }
        }

        /// <remarks />
        [XmlIgnore]
        public bool BitwiseFlagsSpecified
        {
            get
            {
                return _bitwiseFlagsSpecified;
            }
            set
            {
                _bitwiseFlagsSpecified = value;
            }
        }
    }

    /// <remarks />
    [GeneratedCode("xsd", "4.0.30319.17929")]
    [DebuggerStepThrough]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/cmdlets-over-objects/2009/11")]
    public partial class EnumMetadataEnumValue
    {
        private string _name;
        private string _value;

        /// <remarks />
        [XmlAttribute]
        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }

        /// <remarks />
        [XmlAttribute(DataType = "integer")]
        public string Value
        {
            get
            {
                return _value;
            }
            set
            {
                _value = value;
            }
        }
    }
}
